### ISSUE TITLE
REF: MustCompile

### ISSUE THREAD

**Issue by ake-persson** [jaevor/go-nanoid#2]
Would be nice to have MustCompile option like regex module.

*Example with init()*
```
var newNanoId func() string

func init() {
    var err error
    newNanoId, err = nanoid.CustomASCII("0123456789abcdefghijklmnopqrstuvxyz", 4)
    if err != nil {
        panic("nanoid: " + err.Error())
    }
}
```

*This would be nicer*
```
var newNanoId = nanoid.MustCompileCustomASCII("0123456789abcdefghijklmnopqrstuvxyz", 4)
```

**Comment by ErebusBat** [comment]
Created a PR to address this ☝️ .

Given that we are not actually compiling like the regexp example I chose the name `MustCustomASCII` as I thought that was more clear.
