### ISSUE TITLE
As 21 is the "canonic" length for `nanoid.Standard(int length)`, why not add a `nanoid.StandardCanonic()` method?

### ISSUE THREAD

**Issue by Beer4Ever83** [jaevor/go-nanoid#8]
I was wondering if it made sense to create a `nanoid.StandardCanonical()` method (with no parameters) in order to avoid having to remember that `21` is the canonic length every time.

In other words, whoever wants a canonic generator could choose one between:
```
nanoid.Standard(21)
```
or
```
nanoid.StandardCanonic()
```

**Comment by jaevor** [comment]
Sure [https://github.com/jaevor/go-nanoid/releases/tag/v1.4.0](https://github.com/jaevor/go-nanoid/releases/tag/v1.4.0)
